version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - SEQ_URL=http://seq:5341
    depends_on:
      - seq

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - /seq/data:/data
    ports:
      - 5341:80